"""Bounded continuous action distributions used by the policy heads.

Policies that output continuous actions need densities over a box, not over
unconstrained reals. ``SquashedNormal`` maps a Gaussian through tanh onto
``[low, high]``; ``ScaledBeta`` and ``ScaledKumaraswamy`` affine-scale unit-
interval bases onto the same box. ``BoundedIndependent`` reinterprets the
trailing batch dims as event dims while forwarding the ``*_with_z``,
``log_prob_from_z``, and ``z_from_action`` helpers those bases expose, so
agents can train with reparameterized samples and exact log-densities
without summing by hand.
"""

import math
import numpy as np
import torch as T
import torch.nn.functional as F
from torch.distributions import (
    TransformedDistribution, TanhTransform, AffineTransform,
    Beta, Kumaraswamy, Normal, Independent,
)
from torch.distributions.utils import _sum_rightmost


def stable_log1m_tanh_sq(z: T.Tensor) -> T.Tensor:
    """log(1 - tanh(z)^2) computed without ever forming tanh(z).

    Identity: 1 - tanh(z)^2 = 4 / (e^z + e^-z)^2
        => log(1 - tanh(z)^2) = 2 * (log 2 - z - softplus(-2z))

    Exact and finite for all finite z (no epsilon needed).
    """
    return 2.0 * (math.log(2.0) - z - F.softplus(-2.0 * z))


class SquashedNormal(TransformedDistribution):
    """Squashed Normal distribution over ``[low, high]`` for continuous actions."""
    def __init__(
        self,
        base_dist: Normal,
        low:T.Tensor | np.ndarray,
        high:T.Tensor | np.ndarray,
        mc_samples:int = 8,
        epsilon:float = 1e-6
    ):
        """Build a tanh-squashed normal mapped onto ``[low, high]``.

        Args:
            base_dist: Base ``Normal`` over unconstrained ``z``.
            low: Lower bound of the action space.
            high: Upper bound of the action space.
            mc_samples: Monte Carlo samples used by [entropy][phoenx.distributions.SquashedNormal.entropy].
            epsilon: Clamp margin when inverting actions near the bounds.
        """
        device=base_dist.loc.device
        self.low = T.as_tensor(low, dtype=T.float32, device=device)
        self.high = T.as_tensor(high, dtype=T.float32, device=device)
        self.mc_samples = mc_samples
        self.epsilon = epsilon
        self.scale = (self.high - self.low) / 2.0
        self.loc = (self.high + self.low) / 2.0
        self._log_scale = T.log(self.scale)
        transforms = [
            TanhTransform(cache_size=1),
            AffineTransform(loc=self.loc, scale=self.scale, cache_size=1),
        ]
        super().__init__(base_dist, transforms)

    def rsample_with_z(self, sample_shape=T.Size()) -> tuple[T.Tensor, T.Tensor]:
        """Reparameterized sample with gradients flowing through both bounded action and raw action(z).

        Args:
            sample_shape (T.Size): The shape of the sample.

        Returns:
            tuple[T.Tensor, T.Tensor]: The reparameterized sample(action) and the raw sample(z).
        """
        z = self.base_dist.rsample(sample_shape)
        actions = self.loc + self.scale * T.tanh(z)
        return actions, z

    def sample_with_z(self, sample_shape=T.Size()) -> tuple[T.Tensor, T.Tensor]:
        """Sample bounded action and raw action(z) without gradients.

        Args:
            sample_shape (T.Size): The shape of the sample.

        Returns:
            tuple[T.Tensor, T.Tensor]: The sampled bounded action and the raw sample(z).
        """
        with T.no_grad():
            return self.rsample_with_z(sample_shape)

    def log_prob_from_z(self, z: T.Tensor) -> T.Tensor:
        """Per-dimension log-density of action(bounded) from raw sample(z).

        Args:
            z (T.Tensor): The raw sample(z).

        Returns:
            T.Tensor: The per-dimension log-density of the action. Shape: (batch, action_dim). (Independent sums over action_dim).
        """
        return self.base_dist.log_prob(z) - stable_log1m_tanh_sq(z) - self._log_scale

    def mean_with_z(self) -> tuple[T.Tensor, T.Tensor]:
        """Deterministic mean action (tanh of base mean) and its raw/base mean (z).

        Returns:
            tuple[T.Tensor, T.Tensor]: The deterministic mean action and the raw/base mean(z).
        """
        z = self.base_dist.mean
        return self.loc + self.scale * T.tanh(z), z

    def z_from_action(self, actions: T.Tensor) -> T.Tensor:
        """Safe inverse for actions not generated by the policy (e.g. warmup sample actions).

        Args:
            actions (T.Tensor): The actions to invert.

        Returns:
            T.Tensor: The raw sample(z).
        """
        y = (actions - self.loc) / self.scale
        y = y.clamp(min=-1.0 + self.epsilon, max=1.0 - self.epsilon)
        return 0.5 * (y.log1p() - (-y).log1p())

    def log_prob(self, actions: T.Tensor) -> T.Tensor:
        """Finite but biased near bounds. Use log_prob_from_z instead.

        Args:
            actions (T.Tensor): The actions.

        Returns:
            T.Tensor: The log-density of the actions. Shape: (batch, action_dim). (Independent sums over action_dim).
        """
        return self.log_prob_from_z(self.z_from_action(actions))

    def entropy(self) -> T.Tensor:
        """MC estimate; per-dimension (Independent sums over action_dim).
        
        Returns:
            T.Tensor: The entropy of the distribution. Shape: (batch, action_dim). (Independent sums over action_dim).
        """
        z = self.base_dist.rsample((self.mc_samples,))
        log_det_jacobian = stable_log1m_tanh_sq(z)
        return self.base_dist.entropy() + log_det_jacobian.mean(0) + self._log_scale


class ScaledBeta(TransformedDistribution):
    """Beta distribution scaled to ``[low, high]`` bounds."""
    def __init__(
        self,
        base_dist: Beta,
        low:T.Tensor | np.ndarray,
        high:T.Tensor | np.ndarray,
        epsilon:float = 1e-6
    ):
        """Build a Beta distribution affine-scaled onto ``[low, high]``.

        Args:
            base_dist: Base ``Beta`` over the unit interval.
            low: Lower bound of the action space.
            high: Upper bound of the action space.
            epsilon: Clamp margin when inverting actions near the bounds.
        """
        device = base_dist.concentration0.device
        self.low = T.as_tensor(low, dtype=T.float32, device=device)
        self.high = T.as_tensor(high, dtype=T.float32, device=device)
        self.epsilon = epsilon
        self._range = self.high - self.low
        self.log_scale = T.log(self._range)
        transforms = [AffineTransform(loc=self.low, scale=self._range, cache_size=1)]
        super().__init__(base_dist, transforms)

    def rsample_with_z(self, sample_shape=T.Size()) -> tuple[T.Tensor, T.Tensor]:
        """Reparameterized sample with gradients flowing through both bounded action and raw action(z).

        Args:
            sample_shape (T.Size): The shape of the sample.

        Returns:
            tuple[T.Tensor, T.Tensor]: The reparameterized sample(action) and the raw sample(z).
        """
        z = self.base_dist.rsample(sample_shape)
        return self.low + self._range * z, z

    def sample_with_z(self, sample_shape=T.Size()) -> tuple[T.Tensor, T.Tensor]:
        """Sample bounded action and raw action(z) without gradients.
        
        Args:
            sample_shape (T.Size): The shape of the sample.

        Returns:
            tuple[T.Tensor, T.Tensor]: The sampled bounded action and the raw sample(z).
        """
        with T.no_grad():
            return self.rsample_with_z(sample_shape)

    def log_prob_from_z(self, z: T.Tensor) -> T.Tensor:
        """Per-dimension log-density of action(bounded) from raw sample(z).

        Args:
            z (T.Tensor): The raw sample.

        Returns:
            T.Tensor: The per-dimension log-density of the action. Shape: (batch, action_dim). (Independent sums over action_dim).
        """
        return self.base_dist.log_prob(z) - self.log_scale

    def mean_with_z(self) -> tuple[T.Tensor, T.Tensor]:
        """Deterministic mean action (base mean) and its raw/base mean (z).

        Returns:
            tuple[T.Tensor, T.Tensor]: The deterministic mean action and the raw/base mean(z).
        """
        z = self.base_dist.mean
        return self.low + self._range * z, z

    def z_from_action(self, actions: T.Tensor) -> T.Tensor:
        """Safe inverse for actions not generated by the policy (e.g. warmup sample actions).

        Args:
            actions (T.Tensor): The actions to invert.

        Returns:
            T.Tensor: The raw sample(z).
        """
        return ((actions - self.low) / self._range).clamp(min=self.epsilon, max=1.0 - self.epsilon)

    def entropy(self) -> T.Tensor:
        """Per-dimension entropy of the distribution. (Independent sums over action_dim).
        
        Returns:
            T.Tensor: The entropy of the distribution. Shape: (batch, action_dim). (Independent sums over action_dim).
        """
        return self.base_dist.entropy() + self.log_scale


class ScaledKumaraswamy(TransformedDistribution):
    """Kumaraswamy distribution scaled to ``[low, high]`` bounds."""
    def __init__(
        self,
        base_dist: Kumaraswamy,
        low:T.Tensor | np.ndarray,
        high:T.Tensor | np.ndarray,
        epsilon:float = 1e-6
    ):
        """Build a Kumaraswamy distribution affine-scaled onto ``[low, high]``.

        Args:
            base_dist: Base ``Kumaraswamy`` over the unit interval.
            low: Lower bound of the action space.
            high: Upper bound of the action space.
            epsilon: Clamp margin when inverting actions near the bounds.
        """
        device = base_dist.concentration0.device
        self.low = T.as_tensor(low, dtype=T.float32, device=device)
        self.high = T.as_tensor(high, dtype=T.float32, device=device)
        self.epsilon = epsilon
        self._range = self.high - self.low
        self.log_scale = T.log(self._range)
        transforms = [AffineTransform(loc=self.low, scale=self._range, cache_size=1)]
        super().__init__(base_dist, transforms)

    rsample_with_z = ScaledBeta.rsample_with_z
    sample_with_z = ScaledBeta.sample_with_z
    log_prob_from_z = ScaledBeta.log_prob_from_z
    mean_with_z = ScaledBeta.mean_with_z
    z_from_action = ScaledBeta.z_from_action

    def entropy(self) -> T.Tensor:
        """Per-dimension entropy of the distribution. (Independent sums over action_dim).
        
        Returns:
            T.Tensor: The entropy of the distribution. Shape: (batch, action_dim). (Independent sums over action_dim).
        """
        return self.base_dist.entropy() + self.log_scale


class BoundedIndependent(Independent):
    """``Independent`` wrapper that forwards the bounded z-interface.

    Wraps ``SquashedNormal``, ``ScaledBeta``, or ``ScaledKumaraswamy`` and
    applies the same event-dim reduction to ``log_prob_from_z`` that
    ``Independent`` applies to ``log_prob``.
    """
    def rsample_with_z(self, sample_shape=T.Size()) -> tuple[T.Tensor, T.Tensor]:
        """Reparameterized sample of bounded action and raw ``z``.

        Args:
            sample_shape (torch.Size): Extra leading sample dimensions.

        Returns:
            Bounded action and the pre-transform sample ``z``.
        """
        return self.base_dist.rsample_with_z(sample_shape)

    def sample_with_z(self, sample_shape=T.Size()) -> tuple[T.Tensor, T.Tensor]:
        """Sample bounded action and raw ``z`` without gradients.

        Args:
            sample_shape (torch.Size): Extra leading sample dimensions.

        Returns:
            Bounded action and the pre-transform sample ``z``.
        """
        return self.base_dist.sample_with_z(sample_shape)

    def log_prob_from_z(self, z: T.Tensor) -> T.Tensor:
        """Log-density of the bounded action from raw ``z``, summed over event dims.

        Args:
            z: Pre-transform sample from the base distribution.

        Returns:
            Log-density with the rightmost ``reinterpreted_batch_ndims`` summed.
        """
        lp = self.base_dist.log_prob_from_z(z)
        return _sum_rightmost(lp, self.reinterpreted_batch_ndims)

    def mean_with_z(self) -> tuple[T.Tensor, T.Tensor]:
        """Deterministic mean action and its raw base mean ``z``."""
        return self.base_dist.mean_with_z()

    def z_from_action(self, actions: T.Tensor) -> T.Tensor:
        """Invert a bounded action to the pre-transform sample ``z``.

        Args:
            actions: Bounded actions to invert.

        Returns:
            Pre-transform sample ``z``.
        """
        return self.base_dist.z_from_action(actions)
