device: &device cuda
seed: &seed 42
save_dir: &save_dir "E:/Documents/Programming/Projects/Reinforcement/PhoenX_RL/src/Trained_Models/CartPole-v1_test/Reinforce/"
log_level: info

agent:
  type: Reinforce
  discount: 0.99
  entropy_coefficient: 0.01

env:
  type: gymnasium # "isaacsim" or "gymnasium"
  config:
    # cfg: "isaaclab_tasks.manager_based.classic.cartpole.cartpole_env_cfg:CartpoleEnvCfg"
    cfg: CartPole-v1
    num_envs: 8
    # wrappers: [{"type": "OneHotObservationWrapper", "params": {}}]
    wrappers: []
    render_mode: null
    seed: *seed
    obs_key: null
    goal_key: null
    ach_goal_key: null

models:
  policy:
    layer_config:
      - type: dense
        params: {units: 64, kernel: orthogonal, kernel_params: {gain: 2.0}}
      # - type: relu
      - type: dense
        params: {units: 32, kernel: orthogonal, kernel_params: {gain: 2.0}}
      # - type: relu
    output_config:
      - type: dense
        params: {kernel: orthogonal, kernel_params: {gain: 2.0}}
    optimizer_params: {type: Adam, params: {lr: 0.001}}
    distribution: categorical
    temperature: 1.0
    device: *device

  value:
    layer_config:
      - type: dense
        params: {units: 64, kernel: orthogonal, kernel_params: {gain: 2.0}}
      # - type: relu
      - type: dense
        params: {units: 32, kernel: orthogonal, kernel_params: {gain: 2.0}}
      # - type: relu
    output_config:
      - type: dense
        params: {kernel: orthogonal, kernel_params: {gain: 2.0}}
    optimizer_params: {type: Adam, params: {lr: 0.0001}}
    device: *device

# normalizers:
#   advantage:
#     type: BatchNorm
#     config:
#       momentum: 0.99
#       # update_freq: 1
#       clip_value: 5.0
#       device: *device
#   state:
#     type: RunningNorm
#     config:
#       momentum: 0.99
#       update_freq: 1
#       clip_value: 5.0
#       device: *device

# entropy_schedule:
#   type: "linear"
#   params: {start_factor: 1.0, end_factor: 0.02, total_iters: 15000}

buffer:
  type: TrajectoryBuffer
  config:
    buffer_size: 500
    device: *device

schedule:
  type: OnPolicySchedule
  config:
    unit: episode
    num_units: 1000
    learn_unit: trajectory
    num_learn_units: 10
    seed: *seed

renderer:
  render_freq: 1000
  save_dir: *save_dir

callbacks:
  - type: WandbCallback
    config: {project_name: CartPole-v1}