device: &device cuda
save_dir: &save_dir E:/Documents/Programming/Projects/Reinforcement/PhoenX_RL/src/Trained_Models/LunarLander-v3_test/ActorCritic/
log_level: INFO

schedule:
  stop_unit: timestep
  stop_units: 500000
  learn_every_unit: timestep
  learn_every: 16384
  seed: *seed

agent:
  type: ActorCritic
  config:
    discount: 0.999
    entropy_coefficient: &entropy_coefficient 0.01
    auto_entropy_tuning: false
    entropy_lr: 1.0e-2
    gae_coefficient: 0.98
    policy_grad_clip: 0.5
    value_grad_clip: 0.5
    value_coef: 0.5
    bootstrap_truncations: true
    log_level: INFO
    _diag_freq: 10

env:
  type: gymnasium # "isaacsim" or "gymnasium"
  config:
    # cfg: "isaaclab_tasks.manager_based.classic.cartpole.cartpole_env_cfg:CartpoleEnvCfg"
    cfg: LunarLander-v3
    num_envs: 16
    # wrappers: [{"type": "OneHotObservationWrapper", "params": {}}]
    wrappers: []
    render_mode: null
    seed: *seed
    obs_key: null
    goal_key: null
    ach_goal_key: null

models:
  policy:
    layer_config:
      - type: dense
        params: {units: 64, kernel: default, kernel_params: {}}
      - type: tanh
      - type: dense
        params: {units: 64, kernel: default, kernel_params: {}}
      - type: tanh
    output_config:
      - type: dense
        params: {kernel: default, kernel_params: {}}
    optimizer_params: {type: RMSprop, params: {lr: 7.0e-4, eps: 1.0e-5, alpha: 0.99}}
    distribution: categorical
    temperature: &temperature 1.0
    device: *device

  value:
    layer_config:
      - type: dense
        params: {units: 64, kernel: default, kernel_params: {}}
      - type: tanh
      - type: dense
        params: {units: 64, kernel: default, kernel_params: {}}
      - type: tanh
    output_config:
      - type: dense
        params: {kernel: default, kernel_params: {}}
    optimizer_params: {type: RMSprop, params: {lr: 7.0e-4, eps: 1.0e-5, alpha: 0.99}}
    device: *device

normalizers:
  advantage:
    type: BatchNorm
    config:
      clip_value: 10.0
      device: *device
      log_level: INFO
      # kwargs
      # _diag_freq: 4096
  state:
    type: RunningNorm
    config:
      clip_value: 10.0
      warmup_steps: 1000
      device: *device
      log_level: INFO
      # kwargs
      # _diag_freq: 4096
  reward:
    type: RewardNorm
    config:
      gamma: 0.99
      clip_value: 10.0
      device: *device
      log_level: INFO
      # kwargs
      _diag_freq: 1024

# entropy_schedule:
#   schedule_type: "linear"
#   steps: 100000
#   start_value: *entropy_coefficient
#   end_value: 0.001

# temperature_schedule:
#   schedule_type: "cosine"
#   steps: 500000
#   start_value: *temperature
#   end_value: 1.0

buffer:
  type: RolloutBuffer
  config:
    buffer_size: 1024
    device: *device

renderer:
  render_freq: 1000
  save_dir: *save_dir

callbacks:
  - type: WandbCallback
    config: {project_name: LunarLander-v3}