# DDPG tuned for FetchPickAndPlace-v4

device: &device cuda
save_dir: &save_dir E:/Documents/Programming/Projects/Reinforcement/PhoenX_RL/src/Trained_Models/FetchPickAndPlace-v4/DDPG/
log_level: INFO

schedule:
  stop_unit: timestep
  stop_units: &stop_units 5000000
  learn_every_unit: episode
  learn_every: 16
  updates_per_learn: 40
  batch_size: 512
  warmup_steps: 20000
  seed: &seed 42

agent:
  type: DDPG
  config:
    name: DDPG
    policy:
      layer_config:
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
      output_config:
        - type: dense
          params: {kernel: uniform, kernel_params: {a: -0.003, b: 0.003}}
      optimizer_params: {type: Adam, params: {lr: &policy_lr 1.0e-3}}
      # lr_scheduler:
      #   schedule_type: "cosine"
      #   steps: *stop_units
      #   start_value: *policy_lr
      #   end_value: 1.0e-4
      device: *device
    critic:
      layer_config: []
      merged_config:
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
      output_config:
        - type: dense
          params: {kernel: uniform, kernel_params: {a: -0.003, b: 0.003}}
      optimizer_params: {type: Adam, params: {lr: &critic_lr 1.0e-3}}
      # lr_scheduler:
      #   schedule_type: "cosine"
      #   steps: *stop_units
      #   start_value: *critic_lr
      #   end_value: 1.0e-4
      device: *device
    discount: 0.98
    tau: 0.05
    action_epsilon: 0.2
    state_normalizer:
      type: RunningNorm
      config:
        name: DDPG.StateNormalizer
        clip_value: 5.0
        device: *device
        log_level: DEBUG
        # kwargs
        _diag_freq: 10000
    noise:
      type: NormalNoise
      config:
        stddev: &noise_stddev 0.1
    noise_schedule:
      schedule_type: linear
      steps: *stop_units
      start_value: *noise_stddev
      end_value: 0.01
    noise_clip: 0.5
    policy_grad_clip: 40.0
    critic_grad_clip: 40.0
    N: &n 3
    intrinsic_motivation:
      type: ICM
      config:
        model_configs: {
          'encoder': {
              'layer_config': [
                  {'type': 'dense', 'params': {units: 64, 'kernel': 'ones', 'kernel params':{}}},
                  {'type': 'relu'},
              ],
              'output_layer': [
                  {'type': 'dense', 'params': {units: 256, 'kernel': 'ones', 'kernel params':{}}}
              ]
          },
          'inverse_model': {
              'layer_config': [
                  {'type': 'dense', 'params': {units: 64, kernel: variance_scaling, 'kernel params':{scale: 1.0, mode: fan_in, distribution: uniform}}},
                  {'type': 'relu'},
              ],
              'output_layer': [
                  {'type': 'dense', 'params': {kernel: variance_scaling, 'kernel params':{scale: 1.0, mode: fan_in, distribution: uniform}}}
              ]
          },
          'forward_model': {
              'layer_config': [
                  {'type': 'dense', 'params': {units: 64, kernel: variance_scaling, 'kernel params':{scale: 1.0, mode: fan_in, distribution: uniform}}},
                  {'type': 'relu'},
              ],
              'output_layer': [
                  {'type': 'dense', 'params': {kernel: variance_scaling, 'kernel params':{scale: 1.0, mode: fan_in, distribution: uniform}}}
              ]
          }
        }
        optimizer_params: {type: Adam, params: {lr: 0.001}}
        reward_weight: &im_reward_weight 0.1
        reward_scheduler:
          schedule_type: linear
          steps: *stop_units
          start_value: *im_reward_weight
          end_value: 0.0
        beta: 0.2
        extrinsic_threshold: 20000
        reward_normalizer:
          type: RewardNorm
          config:
            name: ICM.RewardNormalizer
            gamma: 0.99
            clip_value: 10.0
            device: *device
            log_level: DEBUG
            # kwargs
            _diag_freq: 1000
        device: *device
    log_level: DEBUG
    _diag_freq: 1000

env:
  type: gymnasium # "isaacsim" or "gymnasium" or "envpool"
  config:
    # cfg: "isaaclab_tasks.manager_based.classic.cartpole.cartpole_env_cfg:CartpoleEnvCfg"
    cfg: FetchPickAndPlace-v4
    num_envs: 16
    obs_key: &obs_key observation
    goal_key: &goal_key desired_goal
    ach_goal_key: &ach_goal_key achieved_goal
    wrappers: [{"type": "VectorNStepReward", "params": {"n": *n, "obs_key": *obs_key, "goal_key": *goal_key, "ach_goal_key": *ach_goal_key}}]
    render_mode: null
    seed: *seed

buffer:
  type: PrioritizedReplayBuffer
  config:
    buffer_size: 1000000
    alpha: 0.6
    beta_start: 0.4
    beta_iter: 500000
    priority: rank
    epsilon: 1.0e-6
    N: *n
    hindsight:
      strategy: future
      num_goals: 4
      output_format: n_step
      N: *n
      gamma: 0.99
      device: *device
      relabel_terminations: false
      future_lo: inclusive
      goal_pool: null
    device: *device

# buffer:
#   type: ReplayBuffer
#   config:
#     buffer_size: 1000000
#     N: *n
#     hindsight:
#       strategy: future
#       num_goals: 4
#       output_format: n_step
#       N: *n
#       gamma: 0.98
#       device: *device
#       relabel_terminations: false
#       future_lo: inclusive
#       goal_pool: null
#     device: *device


renderer:
  render_freq: 500 # episodes
  save_dir: *save_dir


callbacks:
  - type: "WandbCallback"
    config: {project_name: "FetchPickAndPlace-v4"}
