<#
.SYNOPSIS
    Writes the machine-local .phoenx-env record for this repo.

.DESCRIPTION
    Records the absolute conda environment prefix (and related fields) so
    activate.ps1 / activate.sh can activate by PREFIX rather than by ambiguous
    environment name. Multiple conda installs on one machine may share names
    like "rl_env"; the prefix is unambiguous.

.PARAMETER Prefix
    Absolute path to the conda env directory (e.g. C:\...\envs\phoenx).

.PARAMETER CondaRoot
    Absolute path to the conda installation root (contains Scripts\conda.exe).

.PARAMETER EnvName
    Environment name (leaf of the prefix under envs\).

.PARAMETER Quiet
    Suppress the confirmation line after a successful write.

.EXAMPLE
    .\scripts\use-env.ps1 -Prefix "C:\Users\jason\miniforge3\envs\phoenx"

.EXAMPLE
    .\scripts\use-env.ps1 -CondaRoot "C:\Users\jason\miniforge3" -EnvName phoenx -Quiet
#>

param(
    [string]$Prefix,
    [string]$CondaRoot,
    [string]$EnvName,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

# -----------------------------------------------------------------------------
# Resolve Prefix / CondaRoot / EnvName
# -----------------------------------------------------------------------------

if ($Prefix) {
    if (-not $EnvName) {
        $EnvName = Split-Path $Prefix -Leaf
    }
    if (-not $CondaRoot) {
        # Typical layout: <root>\envs\<name>. Only accept if conda.exe is there.
        $envsParent = Split-Path $Prefix -Parent
        if ((Split-Path $envsParent -Leaf) -eq "envs") {
            $derivedRoot = Split-Path $envsParent -Parent
            $condaExe = Join-Path $derivedRoot "Scripts\conda.exe"
            if (Test-Path -LiteralPath $condaExe) {
                $CondaRoot = $derivedRoot
            }
        }
        if (-not $CondaRoot) {
            throw "Could not derive conda root from prefix '$Prefix'. Pass -CondaRoot explicitly."
        }
    }
}
elseif ($CondaRoot -and $EnvName) {
    $Prefix = Join-Path $CondaRoot "envs\$EnvName"
}
else {
    throw @"
Usage: use-env.ps1 -Prefix <env-prefix>
   or: use-env.ps1 -CondaRoot <conda-root> -EnvName <name>
"@
}

# -----------------------------------------------------------------------------
# Validate before writing
# -----------------------------------------------------------------------------

if (-not (Test-Path -LiteralPath $Prefix -PathType Container)) {
    throw "Environment prefix does not exist: $Prefix"
}

$pythonExe = Join-Path $Prefix "python.exe"
if (-not (Test-Path -LiteralPath $pythonExe)) {
    throw "No python.exe under prefix: $pythonExe"
}

$condaExe = Join-Path $CondaRoot "Scripts\conda.exe"
if (-not (Test-Path -LiteralPath $condaExe)) {
    throw "No conda.exe under conda root: $condaExe"
}

# -----------------------------------------------------------------------------
# Write .phoenx-env (LF, UTF-8 no BOM)
# -----------------------------------------------------------------------------
# Single-quoted values: bash sources this file directly; inside single quotes
# a backslash is literal, so Windows paths survive intact.
# LF + no BOM: PowerShell 5.1 Set-Content defaults to CRLF / UTF8-with-BOM,
# either of which corrupts bash `source` (trailing CR in values, BOM on line 1).

$repoRoot = Split-Path $PSScriptRoot -Parent
$recordPath = Join-Path $repoRoot ".phoenx-env"

$lines = @(
    "# Generated by PhoenX. Machine-local; not tracked by git."
    "PHOENX_CONDA_ROOT='$CondaRoot'"
    "PHOENX_ENV_NAME='$EnvName'"
    "PHOENX_ENV_PREFIX='$Prefix'"
)
$content = ($lines -join "`n") + "`n"
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($recordPath, $content, $utf8NoBom)

if (-not $Quiet) {
    Write-Host "Recorded PhoenX env prefix: $Prefix" -ForegroundColor Green
}
