# SAC tuned for FetchPickAndPlace-v4

device: &device cuda
save_dir: &save_dir E:/Documents/Programming/Projects/Reinforcement/PhoenX_RL/src/Trained_Models/IsaacSim/Franka/Reach/JointPos/SAC_1/
log_level: INFO

schedule:
  stop_unit: timestep
  stop_units: &stop_units 10000000
  learn_every_unit: timestep
  learn_every: 512
  updates_per_learn: 1
  batch_size: 512
  warmup_steps: 20000
  seed: &seed 42

agent:
  type: SAC
  config:
    name: SAC
    policy:
      layer_config:
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
      output_config:
        - type: dense
          params: {kernel: uniform, kernel_params: {a: -3.0e-3, b: 3.0e-3}}
      optimizer_params: {type: Adam, params: {lr: &policy_lr 3.0e-4}}
      distribution: normal
      device: *device
    critic:
      layer_config: []
      merged_config:
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
        - type: dense
          params: {units: 64, kernel: variance_scaling, kernel_params: {scale: 1.0, mode: fan_in, distribution: uniform}}
        - type: relu
      output_config:
        - type: dense
          params: {kernel: uniform, kernel_params: {a: -3.0e-3, b: 3.0e-3}}
      optimizer_params: {type: Adam, params: {lr: &critic_lr 3.0e-4}}
      device: *device
    discount: 0.99
    tau: 0.005
    state_normalizer:
      type: RunningNorm
      config:
        name: SAC.StateNormalizer
        clip_value: 5.0
        device: *device
        log_level: DEBUG
        _diag_freq: 10000
    # entropy_coefficient: 0.2
    auto_entropy_tuning: true
    # entropy_lr: 0.0001
    # target_entropy_scale: 0.98
    policy_grad_clip: 40.0
    critic_grad_clip: 40.0
    critic_huber_delta: 1.0
    N: &n 1
    # intrinsic_motivation:
    #   type: ICM
    #   config:
    #     model_configs: {
    #       'encoder': {
    #           'layer_config': [
    #               {'type': 'dense', 'params': {units: 64, kernel: variance_scaling, kernel_params:{scale: 1.0, mode: fan_in, distribution: uniform}}},
    #               {'type': 'relu'},
    #           ],
    #           'output_layer': [
    #               {'type': 'dense', 'params': {units: 256, kernel: variance_scaling, kernel_params:{scale: 1.0, mode: fan_in, distribution: uniform}}}
    #           ]
    #       },
    #       'inverse_model': {
    #           'layer_config': [
    #               {'type': 'dense', 'params': {units: 64, kernel: variance_scaling, kernel_params:{scale: 1.0, mode: fan_in, distribution: uniform}}},
    #               {'type': 'relu'},
    #           ],
    #           'output_layer': [
    #               {'type': 'dense', 'params': {kernel: variance_scaling, kernel_params:{scale: 1.0, mode: fan_in, distribution: uniform}}}
    #           ]
    #       },
    #       'forward_model': {
    #           'layer_config': [
    #               {'type': 'dense', 'params': {units: 64, kernel: variance_scaling, kernel_params:{scale: 1.0, mode: fan_in, distribution: uniform}}},
    #               {'type': 'relu'},
    #           ],
    #           'output_layer': [
    #               {'type': 'dense', 'params': {kernel: variance_scaling, kernel_params:{scale: 1.0, mode: fan_in, distribution: uniform}}}
    #           ]
    #       }
    #     }
    #     optimizer_params: {type: Adam, params: {lr: 0.001}}
    #     reward_weight: &im_reward_weight 0.1
    #     reward_scheduler:
    #       schedule_type: linear
    #       steps: *stop_units
    #       start_value: *im_reward_weight
    #       end_value: 0.0
    #     beta: 0.2
    #     extrinsic_threshold: 20000
    #     reward_normalizer:
    #       type: RewardNorm
    #       config:
    #         name: ICM.RewardNormalizer
    #         gamma: 0.99
    #         clip_value: 10.0
    #         device: *device
    #         log_level: DEBUG
    #         # kwargs
    #         _diag_freq: 1000
    #     device: *device
    log_level: DEBUG
    _diag_freq: 1000

env:
  type: isaacsim
  config:
    cfg: "isaaclab_tasks.manager_based.manipulation.reach.config.franka.joint_pos_env_cfg:FrankaReachEnvCfg"
    num_envs: 512
    obs_key: &obs_key policy
    goal_key: &goal_key null
    ach_goal_key: &ach_goal_key null
    wrappers: [{"type": "VectorNStepReward", "params": {"n": *n, "obs_key": *obs_key, "goal_key": *goal_key, "ach_goal_key": *ach_goal_key}}]
    render_mode: headless
    seed: *seed

# buffer:
#   type: PrioritizedReplayBuffer
#   config:
#     buffer_size: 1000000
#     alpha: 0.6
#     beta_start: 0.4
#     beta_iter: 500000
#     priority: rank
#     sort_freq: 5120
#     epsilon: 1.0e-6
#     N: *n
#     # hindsight:
#     #   strategy: future
#     #   num_goals: 4
#     #   output_format: n_step
#     #   N: *n
#     #   gamma: 0.99
#     #   device: *device
#     #   relabel_terminations: false
#     #   future_lo: inclusive
#     #   goal_pool: null
#     device: *device

buffer:
  type: ReplayBuffer
  config:
    buffer_size: 1000000
    N: *n
    # hindsight:
    #   strategy: future
    #   num_goals: 4
    #   output_format: n_step
    #   N: *n
    #   gamma: 0.99
    #   device: *device
    #   relabel_terminations: false
    #   future_lo: inclusive
    #   goal_pool: null
    device: *device

# renderer:
#   render_freq: 500
#   save_dir: *save_dir

callbacks:
  - type: "WandbCallback"
    config: {project_name: IsaacSimFrankaReachJointPos}
