name: rl_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pylint
  - pytest
  - numpy
  - pandas
  - numba
  - umap-learn
  - pynndescent
  - matplotlib
  - seaborn
  - scikit-learn
  - astunparse
  - hypothesis
  - psutil
  - pyyaml
  - requests
  - setuptools
  - typing-extensions>=4.8.0
  - sympy
  - filelock
  - networkx
  - jinja2
  - fsspec
  - packaging
  - lark
  - ipykernel
  - ale-py
  - flask
  - dash
  - natsort
  - moviepy
  - ffmpeg
  - mpi4py
  - cupy
  - dash-bootstrap-components
  # - jaxlib=0.4.26  # If needed
  # - mujoco         # If needed
  - pip:
    - expecttest!=0.2.0
    - optree>=0.9.1
    - ale-py
    - autorom
    # - dash-bootstrap-components
    - wandb
    - types-dataclasses
    - gymnasium[all]==1.0.0
    - gymnasium-robotics
    - decorator==4.0.2
