name: rl_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pylint
  - pytest
  - numpy
  - pandas
  - numba
  - umap-learn
  - pynndescent
  - matplotlib
  - seaborn
  - scikit-learn
  - astunparse
  - hypothesis
  - psutil
  - pyyaml
  - requests
  - setuptools
  - typing-extensions>=4.8.0
  - sympy
  - filelock
  - networkx
  - jinja2
  - fsspec
  - packaging
  - lark
  - ipykernel
  - ale-py
  - flask
  - dash
  - natsort
  - moviepy
  - ffmpeg
  - mpi4py
  - dash-bootstrap-components
  - mujoco>=2.2.0,<3.2.0
  - python-dotenv
  - python-dotenv-with-cli
  - ray-all
  - pip:
    - expecttest!=0.2.0
    - optree>=0.9.1
    - ale-py
    - autorom
    - wandb
    - types-dataclasses
    - gymnasium[all]==1.2.0
    # - gymnasium-robotics
    - decorator==4.0.2
    - mcp
    - ipywidgets